# Generated by Django 4.2 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='available', max_length=20),
        ),
    ]
