# Generated by Django 4.2 on 2026-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='condition',
            field=models.CharField(blank=True, default='Good', max_length=100),
        ),
    ]
