# Generated by Django 4.2 on 2026-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('book_issued', 'Book Issued'), ('book_returned', 'Book Returned'), ('book_overdue', 'Book Overdue'), ('fine_created', 'Fine Created'), ('fine_paid', 'Fine Paid'), ('reservation_ready', 'Reservation Ready'), ('reservation_cancelled', 'Reservation Cancelled')], max_length=50),
        ),
    ]
