# Generated by Django 4.2 on 2026-08-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_entity_id',
            field=models.IntegerField(blank=True, help_text='ID of the related loan, fine, or reservation', null=True),
        ),
    ]
