# Generated by Django 4.2 on 2026-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
