# Generated by Django 4.2 on 2026-07-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('circulation', '0002_reservation_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allocated_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_reservations', to='inventory.bookcopy'),
        ),
    ]
