# Generated by Django 4.2 on 2026-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_reservation_allocated_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
