# Generated by Django 4.2 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_fine_waive_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], max_length=50, null=True),
        ),
    ]
