# Generated by Django 4.2 on 2026-07-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
        ('accounts', '0003_remove_customuser_email_verified_and_more'),
    ]

    operations = [
    ]
