# Generated by Django 4.2 on 2026-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this member has graduated or been archived.'),
        ),
    ]
